import sys
from appium import webdriver
from time import sleep

if __name__ == '__main__':
    alias = "recarga"
    # remote_url = "http://recargaernesto:188c95c7-37bc-4e3c-8070-5062ec1a42f7@ondemand.saucelabs.com:80/wd/hub"
    remote_url = "http://127.0.0.1:4723/wd/hub"
    desired_caps = {}
    desired_caps['browserName'] = ""
    desired_caps['device-orientation'] = "portrait"
    desired_caps['takesScreenshot'] = 'true'
    desired_caps['platformName'] = 'Android'
    # desired_caps['platformVersion'] = '4.4.4'
    desired_caps['platformVersion'] = '5.1'
    desired_caps['keep_alive'] = 'true'
    # desired_caps['deviceName'] = 'Android Emulator'
    # desired_caps['deviceName'] = 'alpha'
    # desired_caps['deviceName'] = 'K21GLMA561509746'
    desired_caps['deviceName'] = 'TA00403FE4'
    # desired_caps['app'] = 'C:\Users\hzxiadaqiang\PycharmProjects\webscrab\yixin_4.1.0.222_150416_20160107_test.apk'
    # desired_caps['app'] = 'C:\Users\hzxiadaqiang\PycharmProjects\webscrab\yixin_4.1.0.222_150351_20160107_test.apk'
    # desired_caps['app'] = 'C:\Users\hzxiadaqiang\PycharmProjects\webscrab\pris_generic_4.9.5.65.apk'
    # desired_caps['app'] = 'C:\Users\hzxiadaqiang\PycharmProjects\webscrab\Ninja-debug-enable.apk'
    desired_caps['app'] = 'C:\Users\hzxiadaqiang\PycharmProjects\webscrab\selendroid-test-app.apk'
    desired_caps['automationName'] = 'Appium'
    # desired_caps['appPackage'] = 'im.yixin'
    # desired_caps['androidActivity'] = 'im.yixin.'
    desired_caps['language'] = 'zh'
    # desired_caps['locale'] = 'zh-cn'
    desired_caps['appium-version'] = '1.4.14'


    android = webdriver.Remote(remote_url, desired_caps)
    sleep(10)
    android.find_element_by_id('login_btn').click()
    android.find_element_by_id('editUserid').send_keys('15800008888')
    android.find_element_by_id('editPassword').send_keys('123456')
    android.find_element_by_id('btn_login').click()
    sleep(8)
    android.find_element_by_id('btn_login').click()



    """
    android.find_element_by_name('Continuar').click()
    android.find_element_by_name('Continuar').click()
    android.find_element_by_name('Continuar').click()
    android.find_element_by_name('Fazer login com o Facebook').click()
    """
    # contexts = android.contexts
    '''At this point I have two contexts: "WEBVIEW_com.recarga.recarga" and "NATIVE_APP" '''
    android.switch_to.context('NATIVE_APP')
    '''successfull change of context'''
    sleep(10)
    """
    android.find_element_by_name('email').send_keys("recargaernesto@gmail.com")
    android.find_element_by_name('pass').send_keys("hitman123")
    android.find_element_by_name('login').click()
    android.find_element_by_name('__CONFIRM__').click()
    sleep(10)  # switch back to native view
    android.switch_to.context('NATIVE_APP')
    '''Here is where I get the error: selenium.common.exceptions.WebDriverException: Message: {"status": 6, "sessionId": "5c8543c1db394a24921888c7bb035897", "value": ""} That sesion id is the session generated by saucelabs when I connect to the Vm. Saucelabs, starts an appium server internally, the session I'm lost is the one for this server. '''
    """
    android.quit()